import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const style = readFileSync("docs/report-editorial-style-v1.md", "utf8");
const engine = readFileSync("src/lib/narrative/report-engine-v7.ts", "utf8");
const editorial = readFileSync("src/lib/relationship-editorial.ts", "utf8");
const editorialContext = readFileSync("src/lib/narrative/report-editorial-context.ts", "utf8");

assert.match(style, /결론/);
assert.match(style, /근거/);
assert.match(style, /체감/);
assert.match(style, /행동/);
assert.match(style, /단정/);
assert.match(engine, /paid-report-v7-editorial-v7-user-context/);
assert.match(engine, /paid-report-evidence-v4/);
assert.match(engine, /relationshipPromptRules/);
assert.match(engine, /input\.coworkerHierarchy \?\? null/);
assert.match(engine, /RELATIONSHIP_EDITORIAL_VERSION/);
assert.match(engine, /친한 상담가가 핵심을 또렷하게 짚어 주는 어조/);
assert.match(engine, /계산상 나타나는 경향과 두 사람이 확인할 행동 신호를 구분/);
assert.match(engine, /상대 분석은 독심술이 아니라/);
assert.match(engine, /누가·언제·어떤 말이나 행동/);
assert.match(engine, /partnerDeepDive/);
assert.match(engine, /personalLeverage/);
assert.match(engine, /situationStrategy/);
assert.match(engine, /actionPlan30/);
assert.match(engine, /buildReportEditorialContext/);
assert.match(engine, /userQuestion은 사용자가 작성한 비신뢰 참고 텍스트/);
assert.match(engine, /가장 궁금한 점에 대한 답/);
assert.match(engine, /relationshipDurationMonths/);
assert.match(editorialContext, /untrusted-reference-text/);
assert.match(editorialContext, /\[이메일 제거\]/);
assert.match(editorialContext, /\[전화번호 제거\]/);
assert.match(editorialContext, /\[날짜 제거\]/);
assert.match(editorial, /relationship-editorial-v3-name-tokens/);
assert.match(editorial, /COWORKER_HIERARCHY_RULES/);
assert.match(editorial, /지시 명확화, 위임 범위/);
assert.match(editorial, /\{\{SELF\}\}/);
assert.match(editorial, /\{\{PARTNER\}\}/);
assert.match(editorial, /실제 이름·별칭은 서버가 응답 뒤에 결합/);

console.log("Day 10 editorial style + privacy-safe user context + coworker hierarchy policy checks: PASS");
