import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const style = readFileSync("docs/report-editorial-style-v1.md", "utf8");
const engine = readFileSync("src/lib/narrative/report-engine-v7.ts", "utf8");
const editorial = readFileSync("src/lib/relationship-editorial.ts", "utf8");
const editorialContext = readFileSync("src/lib/narrative/report-editorial-context.ts", "utf8");

assert.match(style, /결론/);
assert.match(style, /근거/);
assert.match(style, /체감/);
assert.match(style, /행동/);
assert.match(style, /단정/);
assert.match(engine, /paid-report-v7-editorial-v13-saju-boy-magic-school/);
assert.match(engine, /paid-report-evidence-v7/);
assert.match(engine, /relationshipPromptRules/);
assert.match(engine, /input\.coworkerHierarchy \?\? null/);
assert.match(engine, /RELATIONSHIP_EDITORIAL_VERSION/);
assert.match(engine, /핵심 결론을 먼저 말합니다/);
assert.match(engine, /계산된 관계 신호가 가리키는 반응 패턴은 결론형으로 분명하게/);
assert.match(engine, /내부 심리 원인을 사실처럼 발명하지 마세요/);
assert.match(engine, /누가·어떤 상황에서·어떤 말이나 행동/);
assert.match(engine, /내부 심리 원인을 사실처럼 발명하지 마세요/);
assert.match(engine, /연락 횟수, 시간 간격, 주당 횟수/);
assert.match(engine, /오행의 강약·부족·우세를 공감 능력/);
assert.match(engine, /오행의 강약·부족·우세를 공감 능력/);
assert.match(engine, /계산값이 없는 숫자나 비율도 만들지 마세요/);
assert.match(engine, /paidEditorialFacts/);
assert.match(engine, /dayPillar: value\.pillars\.day/);
assert.match(engine, /dominantElements: value\.elementBalance\.strongest/);
assert.match(engine, /lighterElements: value\.elementBalance\.weakest/);
assert.doesNotMatch(engine, /facts: buildPaidReportFacts\(input\),/);
assert.match(engine, /RELATIONSHIP_ROLE_SCORE_ONLY/);
assert.match(engine, /aRoleSupply: _aRoleSupply/);
assert.match(engine, /bRoleSupply: _bRoleSupply/);
assert.match(engine, /normalizedScore: item\.normalizedScore/);
assert.doesNotMatch(engine, /normalizedScore: item\.normalizedScore,\s*maxPoints:/);
assert.match(engine, /partnerDeepDive/);
assert.match(engine, /personalLeverage/);
assert.match(engine, /situationStrategy/);
assert.match(engine, /actionPlan30/);
assert.match(engine, /buildReportEditorialContext/);
assert.match(engine, /userQuestion은 사용자가 작성한 비신뢰 참고 텍스트/);
assert.match(engine, /가장 궁금한 점에 대한 답/);
assert.match(engine, /relationshipDurationMonths/);
assert.match(editorialContext, /untrusted-reference-text/);
assert.match(editorialContext, /\[이메일 제거\]/);
assert.match(editorialContext, /\[전화번호 제거\]/);
assert.match(editorialContext, /\[날짜 제거\]/);
assert.match(editorial, /relationship-editorial-v3-name-tokens/);
assert.match(editorial, /COWORKER_HIERARCHY_RULES/);
assert.match(editorial, /지시 명확화, 위임 범위/);
assert.match(editorial, /\{\{SELF\}\}/);
assert.match(editorial, /\{\{PARTNER\}\}/);
assert.match(editorial, /실제 이름·별칭은 서버가 응답 뒤에 결합/);

console.log("Day 10 editorial style + reduced AI facts + privacy-safe user context policy checks: PASS");
