import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const theme = readFileSync("src/app/report-theme.css", "utf8");
const base = readFileSync("src/app/report-v2-base.css", "utf8");
const detail = readFileSync("src/app/report-v2-detail.css", "utf8");
const overrides = readFileSync("src/app/report-p5-overrides.css", "utf8");
const mobile = readFileSync("src/app/report-p5-mobile.css", "utf8");
const page = readFileSync("src/app/one-to-one/result/page.tsx", "utf8");
const result = readFileSync("src/app/one-to-one/result/result-v2.tsx", "utf8");
const resultLayout = readFileSync("src/app/one-to-one/result/report-layout-v3.tsx", "utf8");
const resultLayoutCss = readFileSync("src/app/one-to-one/result/report-layout-v3.module.css", "utf8");
const resultStatusCss = readFileSync("src/app/one-to-one/result/result-status.css", "utf8");
const narrativeV8 = readFileSync("src/lib/narrative/report-engine-v8.ts", "utf8");
const components = readFileSync("src/app/one-to-one/result/report-v2-components.tsx", "utf8");
const oneToOnePage = readFileSync("src/app/one-to-one/page.tsx", "utf8");
const oneToOneInputCss = readFileSync("src/app/one-to-one/one-to-one-input-v3.module.css", "utf8");
const checkout = readFileSync("src/app/one-to-one/checkout/page.tsx", "utf8");
const oneToOneFlowCss = readFileSync("src/app/one-to-one/one-to-one-flow.module.css", "utf8");
const payment = readFileSync("src/components/payment-button.tsx", "utf8");
const share = readFileSync("src/app/one-to-one/result/compatibility-share-card.tsx", "utf8");
const shareCss = readFileSync("src/app/one-to-one/result/compatibility-share-card.module.css", "utf8");
const home = readFileSync("src/app/page.tsx", "utf8");
const homeRecent = readFileSync("src/app/home-recent-reports.tsx", "utf8");
const homeCss = readFileSync("src/app/home-p5.module.css", "utf8");
const siteHeader = readFileSync("src/components/site-header.tsx", "utf8");
const brand = readFileSync("src/components/woorisaju-brand.tsx", "utf8");
const flowStatus = readFileSync("src/components/flow-status-screen.tsx", "utf8");
const mandatoryAuth = readFileSync("src/components/mandatory-auth-gate.tsx", "utf8");
const paymentRedirect = readFileSync("src/app/payment/redirect/page.tsx", "utf8");

for (const token of ["#FFFFFF", "#F3EEFA", "#222026", "#6F6870", "#918991", "#EAE3DD", "#D8CEC7", "#EEE8F2", "#7652D8", "#4D8B5F", "#D55A4A", "#C9973D", "#858E9E", "#3E78A8", "#2F7D4A", "#9A6A12", "#B74343", "#356F9C"]) {
  assert.ok(theme.includes(token), `mobile app theme token missing: ${token}`);
}
assert.doesNotMatch(theme, /prefers-color-scheme:\s*dark/);
assert.match(theme, /Apple SD Gothic Neo/);
assert.match(theme, /--saju-width-report:\s*390px/);
for (const color of ["#E45756", "#EF8A62", "#F3C969", "#86C67C", "#2E9F6B"]) {
  assert.ok(theme.includes(color), `stock-style red-to-green heatmap token missing: ${color}`);
}
assert.match(page, /report-theme\.css/);
assert.match(page, /report-p5-overrides\.css/);
assert.match(page, /report-p5-mobile\.css/);
assert.match(page, /result-status\.css/);
assert.doesNotMatch(page, /generation-loading-v4\.css/);
assert.doesNotMatch(base + detail, /#fbf8f2|#213f33|#fffdf8/i);
assert.match(overrides, /partner-inner-mind-hero/);
assert.match(overrides, /deep-strategy-steps/);

assert.match(home, /home-p5\.module\.css/);
assert.match(home, /이상형 찾기/);
assert.ok(home.indexOf("이상형 찾기") < home.indexOf("1:N 궁합 보기"));
assert.ok(home.indexOf("1:N 궁합 보기") < home.indexOf("1:1 궁합 보기"));
assert.match(home, /HomeRecentReports/);
assert.match(homeRecent, /\/api\/account\/reports/);
assert.match(homeRecent, /\.slice\(0, 3\)/);
assert.match(homeRecent, /profileLabel/);
assert.match(homeRecent, /1:다/);
assert.match(siteHeader, /site-header-home-a99[\s\S]*<AuthStatus/);
assert.match(siteHeader, /WoorisajuBrand/);
assert.match(brand, /woorisaju-brand__chart/);
assert.match(brand, />우리사주</);
for (const candleColor of ["#43b581", "#8162d6", "#ef6a67", "#f0ad38"]) assert.ok(brand.includes(candleColor));
for (const step of ["로그인 확인", "결제 확인", "결과 만들기"]) assert.ok(flowStatus.includes(step));
assert.match(mandatoryAuth, /<FlowStatusScreen/);
assert.match(paymentRedirect, /<FlowStatusScreen/);
assert.match(result, /<FlowStatusScreen/);
assert.match(homeCss, /width:\s*min\(100%,\s*390px\)/);
assert.match(homeCss, /grid-template-columns:\s*repeat\(3/);
assert.match(homeCss, /\.bottomNav/);

assert.match(oneToOnePage, /input-reference-v4\.css/);
assert.match(oneToOnePage, /one-to-one-input-v3\.module\.css/);
assert.match(oneToOnePage, /1:1 궁합 입력/);
assert.match(oneToOneInputCss, /one-to-one-reference-page/);
assert.match(oneToOneInputCss, /#7b46d8/i);
assert.match(checkout, /one-to-one-flow\.module\.css/);
assert.match(oneToOneFlowCss, /var\(--saju-width-compact\)/);
assert.match(oneToOneFlowCss, /@media \(max-width:\s*480px\)/);

assert.match(resultStatusCss, /var\(--saju-width-compact\)/);
assert.match(resultStatusCss, /@media \(max-width:\s*480px\)/);
assert.match(page, /결제와 저장 상태를 확인한 뒤 완성된 리포트를 바로 이어서 보여드려요/);
assert.match(result, /STAGE_COPY/);
assert.match(result, /stageAttempt > 1/);
assert.match(result, /결제는 다시 하지 않아도 됩니다/);
assert.match(result, /recoverPaymentId=/);
assert.match(result, /보통 약 5분이 걸리며/);
assert.doesNotMatch(result, /완료 · \{elapsedSeconds\}|completedSegments/);

assert.match(narrativeV8, /paid-report-v10-woorisaju-direct-voice/);
assert.match(narrativeV8, /전체 세 세그먼트의 사용자 노출 본문이 공백 제외 약 5,000자, 허용 4,000~6,000자/);
assert.match(narrativeV8, /length < 1_050/);
assert.match(narrativeV8, /length < 1_450/);
assert.match(narrativeV8, /length < 1_250/);
assert.match(narrativeV8, /overview\.detailedSummary는 280~420자/);
assert.match(narrativeV8, /chemistry\.dayMaster\/dayBranch\/elements\/yinYang은 각각 140~220자/);
assert.match(narrativeV8, /conflictScenarios는 정확히 3개/);
assert.match(narrativeV8, /relationshipSpecific\.overview는 180~280자/);
assert.match(narrativeV8, /A, B, 나, 상대방 같은 대체 호칭을 사용자 문장에 쓰지 마세요/);
assert.match(narrativeV8, /사주 원국과 궁합 계산 근거에서 출발/);
assert.match(narrativeV8, /시스템 구현 문구를 결과에 노출하지 마세요/);
assert.match(narrativeV8, /사용자에게 보이는 모든 문장은 친근한 반말/);
assert.match(narrativeV8, /전문 용어가 필요하면 먼저 일상 언어로 뜻을 설명/);

assert.match(components, /CompatibilityHeatmap/);
assert.match(components, /핵심 궁합 지표 히트맵/);
assert.match(components, /<details/);
assert.match(components, /근거 보기/);
assert.match(result, /<ReportLayoutV3/);
assert.match(resultLayout, /<CompatibilityHeatmap/);
assert.match(resultLayout, /둘 사이 케미는 어떨까/);
assert.match(resultLayout, /getCompatibilityGrade/);
assert.match(resultLayout, /data-grade=\{grade\}/);
assert.match(resultLayout, /두 사람은 어떤 기운을 가졌을까/);
assert.match(resultLayout, /둘이 붙으면 어떤 힘이 살아날까/);
assert.match(resultLayout, /관계의 힘은 어느 쪽으로 흐를까/);
assert.match(resultLayout, /서로 관계에서 무엇을 원할까/);
assert.doesNotMatch(resultLayout, /DayPillarCharacterCard|getDayPillarCharacter/);
assert.doesNotMatch(components, /v2-day-character-note/);
assert.match(resultLayout, /부딪힐 때 어떤 장면이 반복될까/);
assert.match(resultLayout, /지금 이 관계에서 가장 중요한 건 뭘까/);
assert.doesNotMatch(resultLayout, /장기 전망|관계 사용설명서|리포트 목차|이 관계를 살리는 힘|반복 주의 지점/);
assert.doesNotMatch(resultLayout, /threeYearTiming|대운·세운|3년 흐름/);
assert.match(result, /dimension !== "luckCycleAlignment"/);
assert.match(resultLayoutCss, /width:min\(100%,390px\)/);
assert.match(resultLayoutCss, /@media\(max-width:360px\)/);
assert.match(resultLayoutCss, /@media\(min-width:430px\)/);
assert.doesNotMatch(resultLayout, /나의 사주|상대의 사주|label=\"나의 캐릭터\"|label=\"상대의 캐릭터\"/);
assert.match(components, /무슨 뜻일까/);
assert.match(components, /두 사람에게는/);
assert.match(result, /v2-reading-progress/);
assert.match(checkout, /checkout-sticky-cta/);
assert.match(checkout, /1:1 전체 리포트 보기 · 1,000원/);
assert.match(checkout, /agreementAccepted=\{policyAccepted\}/);
assert.match(payment, /buttonLabel\?: string/);
assert.match(share, /document\.createElement\("canvas"\)/);
assert.match(share, /new File\(\[blob\]/);
assert.match(share, /createPublicShareUrl\(buildOneToOnePublicShare/);
assert.match(share, /SHARE_OPTION = \{ purpose: "recap"/);
assert.match(share, /includeDisplayNames: true/);
assert.doesNotMatch(share, /setIncludeNames|nameToggle/);
assert.doesNotMatch(share, /typeTabs|setPurpose|purpose ===/);
assert.doesNotMatch(share, /accessToken/);
assert.match(shareCss, /aspect-ratio:\s*9 \/ 16/);
assert.match(mobile, /overflow-x:\s*clip/);
assert.ok(result.indexOf("<ReportLayoutV3") < result.indexOf("<CompatibilityShareCard"));

console.log("Jootopi report layout + 5k narrative + honest loading UX contract: PASS");
