import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { PGlite } from "@electric-sql/pglite";
import { NextRequest } from "next/server";
import { createTossNetworkStore,TOSS_NETWORK_CONSENT } from "../src/lib/toss-network-core";
import { createTossNetworkHandler } from "../src/lib/toss-network-handler";
import { TOSS_BASIC_SAMPLE_INPUT,calculateTossBasicResult } from "../src/lib/toss-basic-result";
import { fullbuyChapterKey } from "../src/lib/fullbuy-contract";
import { validateNetwork } from "../apps/toss/src/network-client.js";
import { networkInvite,networkSharePath } from "../apps/toss/src/network-share.js";

async function main() {
  const pg=await PGlite.create();let fail=false;
  const store=createTossNetworkStore({query:async({text,values})=>(await pg.query<Record<string,unknown>>(text,values)).rows,
    transaction:statements=>pg.transaction(async tx=>{const rows=[];for(const {text,values} of statements)rows.push((await tx.query<Record<string,unknown>>(text,values)).rows);
      if(fail){fail=false;await tx.query("SELECT 1/0");}return rows;})},'test-only-key-never-used-in-production-32');
  try {
    const a=TOSS_BASIC_SAMPLE_INPUT.personA,b=TOSS_BASIC_SAMPLE_INPUT.personB;
    const requestId=randomUUID();
    await assert.rejects(store.create('u1',a,false,requestId),/consent_required/);
    await assert.rejects(store.create('u1',{...a,birthDate:'1990-02-30'},true,requestId),/invalid_person/);
    const created=await store.create('u1',a,true,requestId),id=created.network.id;
    const replay=await store.create('u1',a,true,requestId);assert.deepEqual(replay,created);validateNetwork(created.network);
    assert.deepEqual(await store.create('u1',a,true,requestId.toUpperCase()),created);
    await assert.rejects(store.create('u1',{...a,displayName:'변경'},true,requestId),/request_conflict/);
    await assert.rejects(store.view('outsider',id),/not_available/);
    const joined=await store.join('u2',created.invite,b,true);assert.equal(joined.network.members.length,2);
    assert.deepEqual(await store.join('u2',created.invite,b,true),joined);
    await assert.rejects(store.join('u2',created.invite,{...b,birthDate:'1992-10-25'},true),/input_conflict/);
    await assert.rejects(store.join('u3',created.invite,b,true),/join_unavailable/);
    await store.join('u3',created.invite,{...a,displayName:'별'},true);
    await store.join('u4',created.invite,{...b,displayName:'달'},true);
    const view=await store.view('u4',id);assert.equal(view.pairs.length,6);validateNetwork(view);
    const first=created.network.members[0].id,second=joined.network.members.find(m=>m.isSelf)!.id;
    const pair=await store.pair('u4',id,first,second); // Third participant may read another consenting pair.
    const reverse=await store.pair('u4',id,second,first);assert.deepEqual(reverse,pair);
    assert.deepEqual(await store.pair('u4',id.toUpperCase(),first.toUpperCase(),second.toUpperCase()),pair);
    const direct=calculateTossBasicResult({...TOSS_BASIC_SAMPLE_INPUT,personA:first<second?a:b,personB:first<second?b:a});
    assert.deepEqual(pair.result,direct);
    const chapterKey=fullbuyChapterKey(pair.snapshot,'conversation');
    await store.join('u5',created.invite,{...a,displayName:'봄'},true);
    assert.equal(fullbuyChapterKey((await store.pair('u4',id,first,second)).snapshot,'conversation'),chapterKey);
    await assert.rejects(store.pair('outsider',id,first,second),/not_available/);
    await assert.rejects(store.pair('u4',id,first,randomUUID()),/pair_not_available/);
    assert.equal((await store.list('u2')).length,1);assert.deepEqual(await store.list('outsider'),[]);
    const raw=await pg.query<{birth_ciphertext:string;consent_version:string}>("SELECT birth_ciphertext,consent_version FROM woorigunghap_toss_network_members");
    assert.ok(raw.rows.every(r=>!r.birth_ciphertext.includes(a.birthDate)&&r.consent_version===TOSS_NETWORK_CONSENT));
    assert.ok(!JSON.stringify(view).includes('user_id'));assert.ok(!JSON.stringify(view).includes(a.birthDate));
    const original=await pg.query<{birth_ciphertext:string}>("SELECT birth_ciphertext FROM woorigunghap_toss_network_members WHERE id=$1",[first]);
    await pg.query("UPDATE woorigunghap_toss_network_members SET birth_ciphertext=(SELECT birth_ciphertext FROM woorigunghap_toss_network_members WHERE id=$1) WHERE id=$2",[second,first]);
    await assert.rejects(store.pair('u4',id,first,second),/input_integrity_failed/);
    await pg.query("UPDATE woorigunghap_toss_network_members SET birth_ciphertext=$1 WHERE id=$2",[original.rows[0].birth_ciphertext,first]);
    await pg.query("UPDATE woorigunghap_toss_network_members SET consent_version='old' WHERE user_id='u2'");
    await assert.rejects(store.view('u4',id),/consent_expired/);
    await pg.query("UPDATE woorigunghap_toss_network_members SET consent_version=$1 WHERE user_id='u2'",[TOSS_NETWORK_CONSENT]);
    const origin='https://woorisajoo.apps.tossmini.com';
    let identity:{userId:string;provider:string}|null={userId:'u4',provider:'toss'},enabled=true;
    const handler=createTossNetworkHandler({authenticate:async()=>identity,allowedOrigin:v=>v===origin,enabled:()=>enabled,store:()=>store});
    const request=(body:unknown,o=origin)=>handler(new NextRequest('http://localhost/api/toss/network',{method:'POST',headers:{origin:o,'content-type':'application/json'},body:JSON.stringify(body)}));
    const response=await request({action:'pair',networkId:id,memberAId:first,memberBId:second});assert.equal(response.status,200);
    const output=await response.json();assert.deepEqual(output.result,pair.result);assert.equal(output.snapshot,undefined);
    assert.equal(response.headers.get('cache-control'),'private, no-store');
    assert.equal((await request({},'https://evil.example')).status,403);
    identity=null;assert.equal((await request({action:'view',networkId:id})).status,401);
    identity={userId:'u1',provider:'kakao'};assert.equal((await request({action:'view',networkId:id})).status,401);
    identity={userId:'u1',provider:'toss'};enabled=false;assert.equal((await request({action:'view',networkId:id})).status,503);enabled=true;
    assert.equal((await request({padding:'x'.repeat(9000)})).status,400);
    assert.equal((await request({action:'create',person:a,consent:false,requestId:randomUUID()})).status,400);
    await store.leave('u2',id);await assert.rejects(store.view('u2',id),/not_available/);
    await assert.rejects(store.pair('u4',id,first,second),/pair_not_available/);
    await assert.rejects(store.close('u4',id),/not_available/);
    for(let i=6;i<=13;i++)await store.join(`u${i}`,created.invite,{...a,displayName:`가상${i}`},true);
    assert.equal((await store.view('u1',id)).members.length,12);
    await assert.rejects(store.join('u14',created.invite,{...a,displayName:'가득참'},true),/join_unavailable/);
    assert.equal((await store.join('u1',created.invite,a,true)).network.members.length,12);
    fail=true;await assert.rejects(store.create('rollback',a,true,randomUUID()));assert.deepEqual(await store.list('rollback'),[]);
    for(let i=0;i<4;i++)await store.create('u1',a,true,randomUUID());
    await assert.rejects(store.create('u1',a,true,randomUUID()),/create_limit/);
    await store.removeUser('u3');assert.equal((await store.view('u1',id)).members.length,11);
    await pg.query("UPDATE woorigunghap_toss_networks SET expires_at=NOW()-INTERVAL '1 minute' WHERE id=$1",[id]);
    await assert.rejects(store.view('u1',id),/not_available/);await store.purge();
    assert.equal((await pg.query("SELECT * FROM woorigunghap_toss_network_members WHERE network_id=$1",[id])).rows.length,0);
    await store.removeUser('u1');assert.deepEqual(await store.list('u1'),[]);
    const closeRequest=randomUUID(),closed=await store.create('close-user',a,true,closeRequest);
    await store.close('close-user',closed.network.id);
    const reopened=await store.create('close-user',a,true,closeRequest);assert.notEqual(reopened.invite,closed.invite);
    await assert.rejects(store.join('u2',closed.invite,b,true),/not_available/);
    await pg.query("CREATE TABLE woorigunghap_users (user_id TEXT,provider TEXT,provider_user_id TEXT)");
    await pg.query("INSERT INTO woorigunghap_users VALUES ('close-user','toss','123'),('other','kakao','123')");
    await store.removeProviderUser('123');assert.deepEqual(await store.list('close-user'),[]);
    const token='a'.repeat(64),link=networkSharePath(token,'intoss://woorisajoo');assert.equal(networkInvite(link),token);
    const privateLink=networkSharePath(token,'intoss-private://appsintoss?_deploymentId=test-bundle');assert.ok(privateLink.includes('_deploymentId=test-bundle'));
    assert.throws(()=>networkSharePath(token,'intoss-private://appsintoss'));
    assert.throws(()=>networkSharePath(token,'https://evil.example'));
    console.log('Toss private network real SQL: membership/consent/all pairs/privacy/encryption/idempotency/capacity/rollback/expiry/leave/owner removal, route auth/OFF/body/DTO and share paths PASS');
  }finally{await pg.close();}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
